sudo: required

language: sh

services:
  - docker

before_install:
  - export DOCKER_REPO=nlknguyen/shellcheck
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)  

script:
  - docker build -t builder -f Dockerfile_builder .
  - docker run --rm -it -v $(pwd):/mnt builder
  - docker build -t $DOCKER_REPO:$TAG .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_REPO:$TAG
